approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
reviewers:
  members:
  - ericthompson
  - battletoilet
  - Jahnp
  - wdo3650
  - mikewheaton
  - atneik
  - philworthington
  name: default
  required: 2
